[[tree_sitter_bash]]
arch = "aarch64"
git-tree-sha1 = "099c2e1aa6c9781ff77e9aefe08caa0c6b6ac12b"
os = "macos"

    [[tree_sitter_bash.download]]
    sha256 = "cd32b1bc0e0bbe06e12a5802b934ba0cf0d401538cbf6957517204ec07abb6b8"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.aarch64-apple-darwin.tar.gz"
[[tree_sitter_bash]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9b1c6a4aa560d306cb8a8f6bef895792028e2c0"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "21a3715fa339e1a56e0b3b19d27427265cb14f6d62611b6dab8b3490c54f7142"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.aarch64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f58fa8043aa3bea157d83382bc6a2e9262ca807"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "3126c3ca4c1ddb729785438b7b91a2ec27d994a586abce6b6023f01cebfb7ac8"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.aarch64-linux-musl-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "aarch64"
git-tree-sha1 = "adf7440da1d584cdd8e3e89964aee956965317d7"
os = "freebsd"

    [[tree_sitter_bash.download]]
    sha256 = "5c0808a05837d5c0946b5273a19986fa8e66d9a133b895382a24cd2c0eba45de"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.aarch64-unknown-freebsd.tar.gz"
[[tree_sitter_bash]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cac2020030da08a09c9ba0581b621b53a60f266f"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "51b5409a07afaa798207717b5136a46a338d232e28eba46061237c04c407912e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1ebff2b5f5a6120552ffdb24fdfc71604542620"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "a81ac8603234ba6a8c00271fa1d433abab5f4d4e2d8862d452bccf8f11d0d7db"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0edc1d8a22b4f7d15bb1f74083d2515971745b5"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "36fb2f26483d01ccc757137cbb1142815d74940dcc6d2b156cab31c8d1058a61"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d323ffcb2aeccab74eb4df98dea5ea8990db505f"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "1df40b8e3929d411f42b4bc28a3222a8a9720b6102f07e0ce565edf66edf9c1c"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f841d314cb433aacae036c87810d61c3704e8e7"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "959fc1f2ccab1aa9ff77ab26be5bb301b14bdc9de275817046d1c2f52f1a3c34"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.i686-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d0a0ae809b48fbf7163bc7578d3e3937f9c5741"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "add2530a60891ab54cb8490dbbdee04d1367050d29729e095885e03b4209d5c7"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.i686-linux-musl-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f616508214ff2e110b43e7d14741591229776af"
os = "windows"

    [[tree_sitter_bash.download]]
    sha256 = "1f8fa8fc946fc6a2951c8be2218ef5942f79a412bc974c7d112a02669f921209"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.i686-w64-mingw32-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db1a313e5f43a1ab7e6f4654f527e372f485347a"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "c5a128ce9d3f13860e66d480e96939528479ce3824aa2e49fe8c228ea6068071"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59ad9fb8e6d3370eb3b513e8748dcd8447776f39"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "306f5bf1092abbf8606d26438064eab08ed1628eaadce1fe97dee86483ee469b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.riscv64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
git-tree-sha1 = "76480c8823c417787b9bf8345309070ba8d9c311"
os = "macos"

    [[tree_sitter_bash.download]]
    sha256 = "a701f1d5aad58c72daabf5c57e8e9a249eb97adca2a429d67c2dc3b0febc158e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.x86_64-apple-darwin.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "287b63ee34b3d41e102f1dd2375cc2b266688352"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "fdb4be5ec6a88cd666f55aa864c80f5156af7795b38a4294e6bf1ee9210ba1c2"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.x86_64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aed6109d6523f6d42c9ff62acc6c699f961dfdae"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "0f559f5be892525b64e5f430cfc4354a4fe0d09a5afbd9a027367f380c5c13c9"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.x86_64-linux-musl-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
git-tree-sha1 = "1a237db2d73c12bd68448d927e3a51a7fe5add22"
os = "freebsd"

    [[tree_sitter_bash.download]]
    sha256 = "d87a66f5404264523fc0b2216f5bdf949c628606c2ee7d24f8db73c70cc3d8b3"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.x86_64-unknown-freebsd.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "270864ac8779c7834a8302738c5b0c09683dca07"
os = "windows"

    [[tree_sitter_bash.download]]
    sha256 = "5b86c8a7378d108223595395cb392be89614e982be64b3d5d8bb7053350522fa"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.1+0/tree_sitter_bash.v0.25.1.x86_64-w64-mingw32-cxx11.tar.gz"
