[[tree_sitter_bash]]
arch = "aarch64"
git-tree-sha1 = "f6a9614989a8680381d12cd3fe35149aa022c712"
os = "macos"

    [[tree_sitter_bash.download]]
    sha256 = "666f8520fc6a47d77f810046661b76d5f678bfc3caba5f455332129765051f06"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.aarch64-apple-darwin.tar.gz"
[[tree_sitter_bash]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4781eebc89860521e10303a0dbb53e4cc915008"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "77c626271db7cfb918ed72f520a60f1c84ff249b5f019d7c01b6f2c408994e44"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.aarch64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20ee49d7b0eccd745802a7ccd0e10b55c6ad56f5"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "20504962889aee6bef09218a374838554c87f9d1bf4e88284e05340174707c6b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.aarch64-linux-musl-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "aarch64"
git-tree-sha1 = "fe9dc37d3161c65364227ccdf6be4260a37fd94f"
os = "freebsd"

    [[tree_sitter_bash.download]]
    sha256 = "7ae4b2632142539d884f6c68b126b372f1a8fe1f1741103628f9d4548e321763"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.aarch64-unknown-freebsd.tar.gz"
[[tree_sitter_bash]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cee2ee6ccbc8233ca357bf24b800bc599bf8123"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "9de4855cc34ef6ec639473b2270743b2b6607d0de0f143f367b52f4d7bbfe500"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13791b306bd60012feeff479e51e0711dde5d734"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "3e5eb8b068767675adaebadc236999954eae6ecb9fcb323391f092fa0385e735"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7765c5bd58ca11b4e5bb62be91a0de3e20e98a15"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "48619d1b25931219cb0d2832eddd6cc03f3c7bc831afd0aa325df7688f5522a0"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ab2a7b3b57612934e744cee30411162e9e12899"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "36827efa9ba0494c739b89a47de9ebe8a2463abec4b5da860f4348d1cc292f0a"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f63e5a19924359c627863ba737d872e02daebc6"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "b37ef68f93d2aa9f97294939b8819ae449ac0fe5accc302798d7e47864dc2e83"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.i686-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "376af25d5796b344bd413f41866b956b95e2e6ad"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "d5ebf1a54e72fed5fcb6c343e1876a033814f5c863f2779e49203f7801a623a8"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.i686-linux-musl-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22734bb66a0a809a8bcc36273166e2d61cfb2872"
os = "windows"

    [[tree_sitter_bash.download]]
    sha256 = "7c2b4185b04196d47c40d63e501c97c48f6094c4c776bb76366b30e100be4cb3"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.i686-w64-mingw32-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ade743532d4ba74e5ed333576f0868e189835548"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "3a551b991bd0d674026fdba507dad8aabce8a720152d200661d728197da82c23"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "835dba73e7c9b91facd9e767b5726e314700516c"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "7362ea8222f31758776d19d041dc8151af9e8ebfc8e223737a999ca5ad0cdfc0"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.riscv64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
git-tree-sha1 = "039dd17d818bc4e60a5ce89b1d74fb2fda4dacf6"
os = "macos"

    [[tree_sitter_bash.download]]
    sha256 = "9771bc9162d1e3ae9f6ebb5db8a85db7105c21f6ba4a3ba9c8bd769c210fd250"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.x86_64-apple-darwin.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df2d254d4ef5c7d0c349a25431a18ac2cb0b1295"
libc = "glibc"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "97ac76bc096e82e23e17c55aa60942e6bb44ee9222ff1af45895a86282d2404c"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0faf614819168c48241db43c18b519549578bb9"
libc = "musl"
os = "linux"

    [[tree_sitter_bash.download]]
    sha256 = "9ffaf1a356fbd532fa304d5c24e91674b4072a906868d12abf06ce0334767626"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.x86_64-linux-musl-cxx11.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
git-tree-sha1 = "e7022752bb6678d85fa24476ecf7b2514a5a69b8"
os = "freebsd"

    [[tree_sitter_bash.download]]
    sha256 = "49b989a0de7749c782f2389fd5cab02dccf884d0a71faeb5461e0a8e6959136d"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.x86_64-unknown-freebsd.tar.gz"
[[tree_sitter_bash]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf97c20fa4d6bc6ee2df117a0b5f1b246a55f8b2"
os = "windows"

    [[tree_sitter_bash.download]]
    sha256 = "2cf1ed68e00e54767c0d3e0260da188ee04694ce9e123c6de7623dce76ec662e"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_bash_jll.jl/releases/download/tree_sitter_bash-v0.25.0+0/tree_sitter_bash.v0.25.0.x86_64-w64-mingw32-cxx11.tar.gz"
