# Autogenerated wrapper script for tree_sitter_bash_jll for aarch64-apple-darwin
export libtreesitter_bash

JLLWrappers.@generate_wrapper_header("tree_sitter_bash")
JLLWrappers.@declare_library_product(libtreesitter_bash, "@rpath/libtreesitter_bash.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_bash,
        "lib/libtreesitter_bash.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
