# Autogenerated wrapper script for tree_sitter_bash_jll for i686-w64-mingw32-cxx11
export libtreesitter_bash

JLLWrappers.@generate_wrapper_header("tree_sitter_bash")
JLLWrappers.@declare_library_product(libtreesitter_bash, "libtreesitter_bash.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_bash,
        "bin\\libtreesitter_bash.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
